name: Get updated player stats
on:
  schedule:
    - cron: 0 0 1 * *
jobs:
  refresh-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Fetch results from MaxPreps
        uses: JamesIves/fetch-api-data-action@v2.4.0
        with:
          endpoint: https://production.api.maxpreps.com/gatewayweb/react/team-season-player-stats/rollup/v1?teamid=bd12f619-3d60-413e-a9ef-5742cd4a21bb&sportseasonid=1ca63de1-4da1-4fb8-9e2a-040146103fe3
          save-name: softballStats

      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: fetch-api-data-action
          target-folder: client/data/stats
