name: Get updated list of youtube videos
on:
  schedule:
    - cron: 0 0 1,15 1-12 *
jobs:
  refresh-videos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get results from YouTube API
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            curl -H "Accept: application/json" --compressed "https://youtube.googleapis.com/youtube/v3/search?part=snippet&channelId=UCUJYkFyDWcwrf8hED9KUe0w&maxResults=50&order=date&key=${{secrets.KEY}}"
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Store response in json file
        run: echo "$JSON_RESPONSE" > youtubeVideos.json
        working-directory: client/data/youtube

      - name: Adds the file to the repo
        run: git add .
      - name: Commit change to repo
        run: git -c user.email="${{secrets.EMAIL}}" -c user.name="${{secrets.USERNAME}}" commit -am "Update YouTube videos list"
      - name: Push change to repo
        run: git push origin main
